version: '3.9'

services:
  app:
    build:
      context: .  # build from current directory (use ./Dockerfile)
    ports:
      - 8000:8000  # map port 8000 in the container to port 8000 on the host
    volumes:
      - ./app:/app  # map the app directory on . to the /app directory on the docker container
